import {
    AfterUpsert,
    BeforeCreate,
    BeforeUpdate,
    BeforeUpsert,
    type EventArgs,
    PrimaryKey,
    Property,
    sql,
} from '@mikro-orm/postgresql';

/**
 * This is the base entity for all records where we want to track created and updated dates.
 */
export abstract class Base {
    @PrimaryKey()
    id!: number;

    // used for data conversion
    @Property({
        type: 'jsonb',
        hidden: true,
        lazy: true,
        nullable: true,
    })
    legacyIds?: JSON;

    @Property({
        returning: true,
        default: sql.now(),
    })
    protected createdAt!: Date;

    @Property({
        returning: false,
        default: sql.now(),
    })
    // Initializing this value seems to help upserts include this field for updates
    protected updatedAt = new Date();

    @BeforeUpdate()
    @BeforeUpsert()
    protected setUpsertFields(_args: EventArgs<Base>): void {
        this.updatedAt = new Date();
    }

    @AfterUpsert()
    protected async setInsertFields(args: EventArgs<Base>): Promise<void> {
        // On insert, timestamp for createdAt is generated by the database and the
        // timestamp for updatedAt is generated in memory; this means that the createdAt
        // can be after the updatedAt timestamp when create happens via upsert
        if (this.createdAt && this.updatedAt < this.createdAt) {
            // Perform a native update so as not to trigger the beforeUpdate lifecycle hook which would
            // change the updatedAt value; also, database generated timestamp uses nanosecond precision
            // while JS uses milliseconds, so we want to be sure the values are equal for create scenarios
            await args.em.nativeUpdate(
                args.meta.className,
                { id: this.id },
                { createdAt: this.createdAt, updatedAt: this.createdAt },
            );
        }
    }

    @BeforeCreate()
    protected setCreateFields(_args: EventArgs<Base>): void {
        const dateTime = new Date();
        this.createdAt = dateTime;
        this.updatedAt = dateTime;
    }
}
